# Generated by Django 4.0 on 2023-08-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='izvrsni_odbor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='skupstina',
            field=models.BooleanField(default=True),
        ),
    ]
