# Generated by Django 4.0 on 2023-08-24 22:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0003_session_izvrsni_odbor_session_skupstina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
