# Generated by Django 4.0 on 2023-08-25 22:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0006_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda_item',
            name='title_cyrillic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title_cyrillic',
            field=models.CharField(blank=True, default='document', max_length=200),
        ),
        migrations.AddField(
            model_name='importantdocument',
            name='title_cyrillic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_cyrillic',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='title_cyrillic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
