# Generated by Django 4.0 on 2023-08-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0009_alter_news_content_cyrillic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='izvrsni_odbor',
        ),
        migrations.RemoveField(
            model_name='session',
            name='skupstina',
        ),
        migrations.AddField(
            model_name='session',
            name='category',
            field=models.CharField(choices=[('skupstina', 'Skupština'), ('izvrsni_odbor', 'Izvršni Odbor')], max_length=200, null=True),
        ),
    ]
