# Generated by Django 4.0 on 2023-08-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0010_remove_session_izvrsni_odbor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda_item',
            options={'verbose_name': 'Session Agenda Item', 'verbose_name_plural': 'Session Agenda Items'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Session Document', 'verbose_name_plural': 'Session Documents'},
        ),
        migrations.AlterModelOptions(
            name='importantdocument',
            options={'verbose_name': 'Single Document', 'verbose_name_plural': 'Single Documents'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='title_cyrillic',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
