# Generated by Django 4.0 on 2023-08-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_profile_user'),
        ('sindikat_app', '0011_alter_agenda_item_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.profile'),
        ),
    ]
