# Generated by Django 4.0 on 2023-08-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_profile_user'),
        ('sindikat_app', '0012_alter_news_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.profile'),
        ),
    ]
