# Generated by Django 4.0 on 2023-09-01 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0013_alter_news_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda_item',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='sindikat_app.session'),
        ),
        migrations.AlterField(
            model_name='agenda_item',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
