# Generated by Django 4.0 on 2023-09-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0015_company_document_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_documents', to='sindikat_app.company'),
        ),
    ]
