# Generated by Django 4.0 on 2023-09-02 11:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0016_alter_document_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='company',
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('title', models.CharField(max_length=200)),
                ('title_cyrillic', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_documents', to='sindikat_app.company')),
            ],
            options={
                'verbose_name': 'Company Document',
                'verbose_name_plural': 'Company Documents',
            },
        ),
    ]
