# Generated by Django 4.0 on 2023-09-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0018_company_company_address_cyrillic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydocument',
            name='title_cyrillic',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address_cyrillic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_job_cyrillic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name_cyrillic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
