# Generated by Django 4.0 on 2023-09-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0019_remove_companydocument_title_cyrillic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='title_cyrillic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
