# Generated by Django 4.0 on 2023-09-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0020_companydocument_title_cyrillic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
    ]
