# Generated by Django 4.0 on 2023-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0021_remove_news_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.ImageField(blank=True, default='ArtBoard2.png', null=True, upload_to=''),
        ),
    ]
