# Generated by Django 4.0 on 2023-09-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0022_news_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='news',
        ),
        migrations.AddField(
            model_name='image',
            name='news',
            field=models.ManyToManyField(blank=True, null=True, related_name='gallery', to='sindikat_app.News'),
        ),
    ]
