# Generated by Django 4.0 on 2023-09-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0024_remove_image_news_image_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='sindikat_app.image'),
        ),
    ]
