# Generated by Django 4.0 on 2023-09-02 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0025_remove_image_news_news_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sindikat_app.news'),
        ),
    ]
