# Generated by Django 4.0 on 2023-09-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0026_remove_news_images_image_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_job',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_job_cyrillic',
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/images/Artboard_2.png', null=True, upload_to=''),
        ),
    ]
