# Generated by Django 4.0 on 2023-09-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0027_remove_company_company_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary')], default='president', max_length=100, null=True),
        ),
    ]
