# Generated by Django 4.0 on 2023-09-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0028_alter_news_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
