# Generated by Django 4.0 on 2023-09-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0030_alter_importantdocument_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='company',
            name='rates',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
