# Generated by Django 4.0 on 2023-09-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0031_alter_news_options_alter_company_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
