# Generated by Django 4.0 on 2023-09-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0033_alter_news_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateField(default=None, null=True),
        ),
    ]
