# Generated by Django 4.0 on 2023-09-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0034_alter_news_created_alter_session_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
