# Generated by Django 4.0 on 2023-09-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0035_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
