# Generated by Django 4.0 on 2023-10-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0036_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.ImageField(blank=True, default='http://192.168.25.78:8000/images/Artboard_2.png', null=True, upload_to=''),
        ),
    ]
