# Generated by Django 4.0 on 2023-10-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0037_alter_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.ImageField(blank=True, default='http://www.apisindikat.skupstina.me/images/Artboard_2.png', null=True, upload_to=''),
        ),
    ]
