# Generated by Django 4.0 on 2023-10-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0039_alter_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.ImageField(blank=True, default='http://apisindikat.skupstina.me/images/ArtBoard_2.png', null=True, upload_to=''),
        ),
    ]
