# Generated by Django 4.0 on 2024-04-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0041_alter_news_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantdocument',
            name='laws',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='importantdocument',
            name='legislation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='importantdocument',
            name='main',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='importantdocument',
            name='other',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='importantdocument',
            name='regulations',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='important',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
