# Generated by Django 4.0 on 2024-04-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindikat_app', '0042_importantdocument_laws_importantdocument_legislation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='draft',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
