# Generated by Django 4.0 on 2023-08-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_president',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
