# Generated by Django 4.0 on 2023-08-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secretary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
